// Generated by gnome-h2d.rb <http://github.com/ddude/gnome.d>.

module glib.glib;

/* GLIB - Library of useful routines for C programming
 * Copyright (C) 1995-1997  Peter Mattis, Spencer Kimball and Josh MacDonald
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/*
 * Modified by the GLib Team and others 1997-2000.  See the AUTHORS
 * file for a list of people on the GLib Team.  See the ChangeLog
 * files for a list of changes.  These files are distributed with
 * GLib at ftp://ftp.gtk.org/pub/gtk/.
 */



//#define __GLIB_H_INSIDE__

public import glib.alloca;
public import glib.array;
public import glib.asyncqueue;
public import glib.atomic;
public import glib.backtrace;
public import glib.base64;
public import glib.bitlock;
public import glib.bookmarkfile;
public import glib.bytes;
public import glib.charset;
public import glib.checksum;
public import glib.convert;
public import glib.dataset;
public import glib.date;
public import glib.datetime;
public import glib.dir;
public import glib.environ;
public import glib.error;
public import glib.fileutils;
public import glib.gettext;
public import glib.hash;
public import glib.hmac;
public import glib.hook;
public import glib.hostutils;
public import glib.iochannel;
public import glib.keyfile;
public import glib.list;
//public import glib.macros;
public import glib.main;
public import glib.mappedfile;
public import glib.markup;
public import glib.mem;
public import glib.messages;
public import glib.node;
public import glib.option;
public import glib.pattern;
public import glib.poll;
public import glib.primes;
public import glib.qsort;
public import glib.quark;
public import glib.queue;
public import glib.rand;
public import glib.regex;
public import glib.scanner;
public import glib.sequence;
public import glib.shell;
public import glib.slice;
public import glib.slist;
public import glib.spawn;
public import glib.strfuncs;
public import glib.string;
public import glib.stringchunk;
public import glib.testutils;
public import glib.thread;
public import glib.threadpool;
public import glib.timer;
public import glib.timezone;
public import glib.trashstack;
public import glib.tree;
public import glib.types;
public import glib.unicode;
public import glib.urifuncs;
public import glib.utils;
public import glib.varianttype;
public import glib.variant;
public import glib.version_;
//public import glib.versionmacros;
/+
#ifdef G_PLATFORM_WIN32
public import glib.win32;
//#endif
+/

//#include <glib/deprecated/gallocator.h>
//#include <glib/deprecated/gcache.h>
//#include <glib/deprecated/gcompletion.h>
//#include <glib/deprecated/gmain.h>
//#include <glib/deprecated/grel.h>
//#include <glib/deprecated/gthread.h>

//#undef __GLIB_H_INSIDE__


