// Generated by gnome-h2d.rb <http://github.com/ddude/gnome.d>.

module glib.gobject;

/* GObject - GLib Type, Object, Parameter and Signal Library
 * Copyright (C) 1998, 1999, 2000 Tim Janik and Red Hat, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 */


//#define __GLIB_GOBJECT_H_INSIDE__

/* topmost include file for GObject header files */
public import gobject.binding;
public import gobject.boxed;
public import gobject.enums;
public import gobject.gobject;
public import gobject.param;
public import gobject.paramspecs;
public import gobject.signal;
public import gobject.sourceclosure;
public import gobject.type;
public import gobject.typemodule;
public import gobject.typeplugin;
public import gobject.value;
public import gobject.valuearray;
public import gobject.valuetypes;

//#undef __GLIB_GOBJECT_H_INSIDE__


