// Generated by gnome-h2d.rb <http://github.com/ddude/gnome.d>.

module glib.shell;

/* gshell.h - Shell-related utilities
 *
 *  Copyright 2000 Red Hat, Inc.
 *
 * GLib is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * GLib is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with GLib; see the file COPYING.LIB.  If not, write
 * to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/+
#if !defined (__GLIB_H_INSIDE__) && !defined (GLIB_COMPILATION)
#error "Only <glib.h> can be included directly."
//#endif
+/



public import glib.error;

extern(C):

//#define G_SHELL_ERROR g_shell_error_quark ()

enum GShellError {
  /* mismatched or otherwise mangled quoting */
  G_SHELL_ERROR_BAD_QUOTING,
  /* string to be parsed was empty */
  G_SHELL_ERROR_EMPTY_STRING,
  G_SHELL_ERROR_FAILED
}

GQuark g_shell_error_quark ();

gchar*   g_shell_quote      (const(gchar)*   unquoted_string);
gchar*   g_shell_unquote    (const(gchar)*   quoted_string,
                             GError       **error);
gboolean g_shell_parse_argv (const(gchar)*   command_line,
                             gint          *argcp,
                             gchar       ***argvp,
                             GError       **error);




