// Generated by gnome-h2d.rb <http://github.com/ddude/gnome.d>.

module gio.dbusobject;

/* GDBus - GLib D-Bus Library
 *
 * Copyright (C) 2008-2010 Red Hat, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Author: David Zeuthen <davidz@redhat.com>
 */



public import gio.types;

extern(C):

//#define G_TYPE_DBUS_OBJECT         (g_dbus_object_get_type())
//#define G_DBUS_OBJECT(o)           (G_TYPE_CHECK_INSTANCE_CAST ((o), G_TYPE_DBUS_OBJECT, GDBusObject))
//#define G_IS_DBUS_OBJECT(o)        (G_TYPE_CHECK_INSTANCE_TYPE ((o), G_TYPE_DBUS_OBJECT))
//#define G_DBUS_OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE((o), G_TYPE_DBUS_OBJECT, GDBusObjectIface))

//struct _GDBusObjectIface GDBusObjectIface;

/**
 * GDBusObjectIface:
 * @parent_iface: The parent interface.
 * @get_object_path: Returns the object path. See g_dbus_object_get_object_path().
 * @get_interfaces: Returns all interfaces. See g_dbus_object_get_interfaces().
 * @get_interface: Returns an interface by name. See g_dbus_object_get_interface().
 * @interface_added: Signal handler for the #GDBusObject::interface-added signal.
 * @interface_removed: Signal handler for the #GDBusObject::interface-removed signal.
 *
 * Base object type for D-Bus objects.
 *
 * Since: 2.30
 */
struct GDBusObjectIface {
  GTypeInterface parent_iface;

  /* Virtual Functions */
  const(gchar)*     function(GDBusObject  *object) get_object_path;
  GList           *function(GDBusObject  *object) get_interfaces;
  GDBusInterface  *function(GDBusObject  *object,
                                       const(gchar)*  interface_name) get_interface;

  /* Signals */
  void function(GDBusObject     *object,
                             GDBusInterface  *interface_) interface_added;
  void function(GDBusObject     *object,
                             GDBusInterface  *interface_) interface_removed;

};

GType            g_dbus_object_get_type        () pure;
const(gchar)*     g_dbus_object_get_object_path (GDBusObject  *object);
GList           *g_dbus_object_get_interfaces  (GDBusObject  *object);
GDBusInterface  *g_dbus_object_get_interface   (GDBusObject  *object,
                                                const(gchar)*  interface_name);




