// Generated by gnome-h2d.rb <http://github.com/ddude/gnome.d>.

module gio.fileiostream;

/* GIO - GLib Input, Io and Streaming Library
 *
 * Copyright (C) 2006-2007 Red Hat, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Author: Alexander Larsson <alexl@redhat.com>
 */

/+
#if !defined (__GIO_GIO_H_INSIDE__) && !defined (GIO_COMPILATION)
#error "Only <gio/gio.h> can be included directly."
//#endif
+/



public import gio.stream;

extern(C):

//#define G_TYPE_FILE_IO_STREAM         (g_file_io_stream_get_type ())
//#define G_FILE_IO_STREAM(o)           (G_TYPE_CHECK_INSTANCE_CAST ((o), G_TYPE_FILE_IO_STREAM, GFileIOStream))
//#define G_FILE_IO_STREAM_CLASS(k)     (G_TYPE_CHECK_CLASS_CAST((k), G_TYPE_FILE_IO_STREAM, GFileIOStreamClass))
//#define G_IS_FILE_IO_STREAM(o)        (G_TYPE_CHECK_INSTANCE_TYPE ((o), G_TYPE_FILE_IO_STREAM))
//#define G_IS_FILE_IO_STREAM_CLASS(k)  (G_TYPE_CHECK_CLASS_TYPE ((k), G_TYPE_FILE_IO_STREAM))
//#define G_FILE_IO_STREAM_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), G_TYPE_FILE_IO_STREAM, GFileIOStreamClass))

/**
 * GFileIOStream:
 *
 * A subclass of GIOStream for opened files. This adds
 * a few file-specific operations and seeking and truncating.
 *
 * #GFileIOStream implements GSeekable.
 **/
//struct _GFileIOStreamClass    GFileIOStreamClass;
struct _GFileIOStreamPrivate;
alias _GFileIOStreamPrivate* GFileIOStreamPrivate;

struct GFileIOStream {
  GIOStream parent_instance;

  /*< private >*/
  GFileIOStreamPrivate *priv;
};

struct GFileIOStreamClass {
  GIOStreamClass parent_class;

  goffset     function(GFileIOStream    *stream) tell;
  gboolean    function(GFileIOStream    *stream) can_seek;
  gboolean    function(GFileIOStream    *stream,
                                     goffset               offset,
                                     GSeekType             type,
                                     GCancellable         *cancellable,
                                     GError              **error) seek;
  gboolean    function(GFileIOStream    *stream) can_truncate;
  gboolean    function(GFileIOStream    *stream,
                                     goffset               size,
                                     GCancellable         *cancellable,
                                     GError              **error) truncate_fn;
  GFileInfo * function(GFileIOStream    *stream,
                                     const(char)*           attributes,
                                     GCancellable         *cancellable,
                                     GError              **error) query_info;
  void        function(GFileIOStream     *stream,
                                     const(char)*            attributes,
                                     int                   io_priority,
                                     GCancellable         *cancellable,
                                     GAsyncReadyCallback   callback,
                                     gpointer              user_data) query_info_async;
  GFileInfo * function(GFileIOStream     *stream,
                                     GAsyncResult         *result,
                                     GError              **error) query_info_finish;
  char      * function(GFileIOStream    *stream) get_etag;

  /* Padding for future expansion */
  void function() _g_reserved1;
  void function() _g_reserved2;
  void function() _g_reserved3;
  void function() _g_reserved4;
  void function() _g_reserved5;
};

GType      g_file_io_stream_get_type          () pure;

GFileInfo *g_file_io_stream_query_info        (GFileIOStream    *stream,
					       const(char)*           attributes,
					       GCancellable         *cancellable,
					       GError              **error);
void       g_file_io_stream_query_info_async  (GFileIOStream    *stream,
					       const(char)*           attributes,
					       int                   io_priority,
					       GCancellable         *cancellable,
					       GAsyncReadyCallback   callback,
					       gpointer              user_data);
GFileInfo *g_file_io_stream_query_info_finish (GFileIOStream    *stream,
					       GAsyncResult         *result,
					       GError              **error);
char *     g_file_io_stream_get_etag          (GFileIOStream    *stream);




