// Generated by gnome-h2d.rb <http://github.com/ddude/gnome.d>.

module gio.remoteactiongroup;

/*
 * Copyright © 2011 Canonical Limited
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2 of the licence or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authors: Ryan Lortie <desrt@desrt.ca>
 */

/+
#if !defined (__GIO_GIO_H_INSIDE__) && !defined (GIO_COMPILATION)
#error "Only <gio/gio.h> can be included directly."
//#endif
+/



public import gio.types;

extern(C):


//#define G_TYPE_REMOTE_ACTION_GROUP                          (g_remote_action_group_get_type ())
//#define G_REMOTE_ACTION_GROUP(inst)                         (G_TYPE_CHECK_INSTANCE_CAST ((inst),                      
//                                                             G_TYPE_REMOTE_ACTION_GROUP, GRemoteActionGroup))
//#define G_IS_REMOTE_ACTION_GROUP(inst)                      (G_TYPE_CHECK_INSTANCE_TYPE ((inst),                      
//                                                             G_TYPE_REMOTE_ACTION_GROUP))
//#define G_REMOTE_ACTION_GROUP_GET_IFACE(inst)               (G_TYPE_INSTANCE_GET_INTERFACE ((inst),                   
//                                                             G_TYPE_REMOTE_ACTION_GROUP,                              
//                                                             GRemoteActionGroupInterface))

//struct _GRemoteActionGroupInterface                 GRemoteActionGroupInterface;

struct GRemoteActionGroupInterface {
  GTypeInterface g_iface;

  void function(GRemoteActionGroup *remote,
                                     const(gchar)*        action_name,
                                     GVariant           *parameter,
                                     GVariant           *platform_data) activate_action_full;

  void function(GRemoteActionGroup *remote,
                                     const(gchar)*        action_name,
                                     GVariant           *value,
                                     GVariant           *platform_data) change_action_state_full;
};

/+ GLIB_AVAILABLE_IN_2_32 +/
GType                   g_remote_action_group_get_type                  () pure;

/+ GLIB_AVAILABLE_IN_2_32 +/
void                    g_remote_action_group_activate_action_full      (GRemoteActionGroup *remote,
                                                                         const(gchar)*        action_name,
                                                                         GVariant           *parameter,
                                                                         GVariant           *platform_data);

/+ GLIB_AVAILABLE_IN_2_32 +/
void                    g_remote_action_group_change_action_state_full  (GRemoteActionGroup *remote,
                                                                         const(gchar)*        action_name,
                                                                         GVariant           *value,
                                                                         GVariant           *platform_data);




