// Generated by gnome-h2d.rb <http://github.com/ddude/gnome.d>.

module gobject.d;

public {
    import gobject.atomicarray;
    import gobject.binding;
    import gobject.boxed;
    import gobject.closure;
    import gobject.enums;
    import gobject.types;
    import gobject.marshal;
    import gobject.gobject;
    import gobject.object_trace;
    import gobject.param;
    import gobject.paramspecs;
    import gobject.signal;
    import gobject.sourceclosure;
    import gobject.type;
    import gobject.typemodule;
    import gobject.typeplugin;
    import gobject.value;
    import gobject.valuearray;
    import gobject.valuecollector;
    import gobject.valuetypes;
}
